application: social-buzz
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /sitemap.xml
  static_files: public/sitemap.xml
  upload: public/sitemap.xml

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt

- url: /public
  static_dir: public

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: "latest"

- name: webapp2
  version: "latest"


- name: lxml
  version: "latest"
