application: bereg-cn
version: 6
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /sitemap.xml
  static_files: public/sitemap.xml
  upload: public/sitemap.xml

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt

- url: /yandex_5489af98dfdf2ed3.txt
  static_files: public/yandex_5489af98dfdf2ed3.txt
  upload: public/yandex_5489af98dfdf2ed3.txt

- url: /google3b473792790f59d0.html
  static_files: public/google3b473792790f59d0.html
  upload: public/google3b473792790f59d0.html

- url: /public
  static_dir: public

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: "latest"

- name: webapp2
  version: "latest"


- name: lxml
  version: "latest"
